use std::collections::BTreeSet;

const CLI_COMMANDS: &[&str] = &[
    "bijux-dna env images",
    "bijux-dna env info",
    "bijux-dna env doctor",
    "bijux-dna env list",
    "bijux-dna env export-json",
    "bijux-dna env export-containers --json",
    "bijux-dna env export-hpc",
    "bijux-dna env sif-inventory",
    "bijux-dna env ensure",
    "bijux-dna env ensure-images",
    "bijux-dna env lint-apptainer-defs",
    "bijux-dna env smoke",
    "bijux-dna env prep",
    "bijux-dna env apptainer-qa-matrix",
    "bijux-dna registry list-tools",
    "bijux-dna registry list-stages",
    "bijux-dna registry show-tool",
    "bijux-dna registry show-stage",
    "bijux-dna registry show",
    "bijux-dna registry export-json",
    "bijux-dna registry export-containers --json",
    "bijux-dna registry coverage-matrix",
    "bijux-dna registry validate-tool",
    "bijux-dna registry audit",
    "bijux-dna registry doctor",
    "bijux-dna registry promote",
    "bijux-dna registry lint",
    "bijux-dna corpus materialize",
    "bijux-dna corpus normalize",
    "bijux-dna corpus validate",
    "bijux-dna corpus list",
    "bijux-dna corpus diff",
    "bijux-dna fixtures build",
    "bijux-dna fixtures validate",
    "bijux-dna fixtures validate-expected",
    "bijux-dna status",
    "bijux-dna run list-stages",
    "bijux-dna run stages",
    "bijux-dna run doctor",
    "bijux-dna run list-tools",
    "bijux-dna run explain",
    "bijux-dna run validate-pre",
    "bijux-dna run trim",
    "bijux-dna run filter",
    "bijux-dna run merge",
    "bijux-dna run contam",
    "bijux-dna run stats-neutral",
    "bijux-dna run umi",
    "bijux-dna run error-correct",
    "bijux-dna run qc",
    "bijux-dna run align",
    "bijux-dna run preprocess",
    "bijux-dna run run",
    "bijux-dna run compare",
    "bijux-dna run validate",
    "bijux-dna run stats",
    "bijux-dna plan list",
    "bijux-dna plan explain",
    "bijux-dna plan explain-profile",
    "bijux-dna plan validate-profile",
    "bijux-dna plan profile-diff",
    "bijux-dna plan audit",
    "bijux-dna analyze runs",
    "bijux-dna analyze summary",
    "bijux-dna analyze compare",
    "bijux-dna analyze rank",
    "bijux-dna analyze report",
    "bijux-dna analyze metrics",
    "bijux-dna analyze bench",
    "bijux-dna explain runs",
    "bijux-dna explain summary",
    "bijux-dna explain compare",
    "bijux-dna explain rank",
    "bijux-dna explain report",
    "bijux-dna explain metrics",
    "bijux-dna explain bench",
    "bijux-dna bench config validate",
    "bijux-dna bench run",
    "bijux-dna bench status",
    "bijux-dna bench workspace-value",
    "bijux-dna bench config-json",
    "bijux-dna bench repo-checks",
    "bijux-dna bench write-screen-taxonomy-database-lineage",
    "bijux-dna bench validate-matrix",
    "bijux-dna bench publication-targets",
    "bijux-dna bench corpus-fastq",
    "bijux-dna bench normalize-workspace-layout",
    "bijux-dna bench corpus-fastq-report",
    "bijux-dna bench corpus-fastq-publication-status",
    "bijux-dna bench corpus-fastq-published-dossiers",
    "bijux-dna bench readiness render-adapter-missing-input-tests",
    "bijux-dna bench readiness render-expected-benchmark-results",
    "bijux-dna bench readiness render-parser-completeness-gate",
    "bijux-dna bench readiness render-corpus-asset-coverage-gate",
    "bijux-dna bench readiness render-parser-failure-tests",
    "bijux-dna bench readiness render-commands",
    "bijux-dna bench readiness render-command-argv",
    "bijux-dna bench readiness render-stage-tool-containers",
    "bijux-dna bench readiness render-stage-tool-assets",
    "bijux-dna bench readiness render-stage-tool-resources",
    "bijux-dna bench readiness render-bam-adapter-output-contract",
    "bijux-dna bench readiness render-bam-stage-decision-table",
    "bijux-dna bench readiness render-bam-command-adapter-coverage",
    "bijux-dna bench readiness render-bam-corpus-assignment",
    "bijux-dna bench readiness render-corpus-incompatibility",
    "bijux-dna bench readiness render-bam-comparable-metrics",
    "bijux-dna bench readiness render-bam-normalized-metrics-schema",
    "bijux-dna bench readiness render-bam-parser-coverage",
    "bijux-dna bench readiness render-bam-report-map",
    "bijux-dna bench readiness render-fastq-adapter-output-contract",
    "bijux-dna bench readiness render-fastq-command-adapter-coverage",
    "bijux-dna bench readiness render-fastq-comparable-metrics",
    "bijux-dna bench readiness render-fastq-corpus-assignment",
    "bijux-dna bench readiness render-fastq-normalized-metrics-schema",
    "bijux-dna bench readiness render-fastq-parser-coverage",
    "bijux-dna bench readiness render-fastq-report-map",
    "bijux-dna bench readiness render-fastq-tool-serving-map",
    "bijux-dna bench readiness render-bam-tool-serving-map",
    "bijux-dna bench readiness render-missing-result-report",
    "bijux-dna bench readiness render-pair-readiness",
    "bijux-dna bench readiness render-corpus-centric-report",
    "bijux-dna bench readiness render-benchmark-readiness-dashboard",
    "bijux-dna bench readiness render-stage-tool-benchmark-ready",
    "bijux-dna bench readiness render-stage-centric-report",
    "bijux-dna bench readiness render-tool-centric-report",
    "bijux-dna bench readiness render-missing-benchmark-pairs",
    "bijux-dna bench readiness render-tool-id-normalization",
    "bijux-dna bench readiness render-stage-registry-extra-pairs",
    "bijux-dna bench readiness render-unregistered-benchmark-pairs",
    "bijux-dna bench readiness render-orphan-tools",
    "bijux-dna bench readiness render-undercovered-stages",
    "bijux-dna bench readiness validate-tool-execution-modes",
    "bijux-dna bench readiness validate-tool-families",
    "bijux-dna bench local list-stages",
    "bijux-dna bench local render-vcf-stage-catalog",
    "bijux-dna bench local render-vcf-stage-matrix",
    "bijux-dna bench local render-vcf-smoke-root",
    "bijux-dna bench local run-vcf-call-smoke",
    "bijux-dna bench local run-vcf-call-diploid-smoke",
    "bijux-dna bench local run-vcf-call-gl-smoke",
    "bijux-dna bench local run-vcf-damage-filter-smoke",
    "bijux-dna bench local run-vcf-filter-smoke",
    "bijux-dna bench local run-vcf-qc-smoke",
    "bijux-dna bench local run-vcf-pca-smoke",
    "bijux-dna bench local run-vcf-stats-smoke",
    "bijux-dna bench local run-vcf-gl-propagation-smoke",
    "bijux-dna bench local run-vcf-prepare-reference-panel-smoke",
    "bijux-dna bench local run-vcf-phasing-smoke",
    "bijux-dna bench local run-vcf-impute-smoke",
    "bijux-dna bench local run-vcf-imputation-metrics-smoke",
    "bijux-dna bench local run-vcf-call-pseudohaploid-smoke",
    "bijux-dna bench local validate-vcf-no-empty-output",
    "bijux-dna bench local validate-vcf-stage-catalog-ready",
    "bijux-dna bench local validate-vcf-reference-compatibility",
    "bijux-dna bench local validate-vcf-sample-compatibility",
    "bijux-dna bench local validate-hpc-submission-ready",
    "bijux-dna bench local simulate-dag-watchdog",
    "bijux-dna bench local validate-pipeline-dag",
    "bijux-dna bench local validate-corpus-fixture",
    "bijux-dna bench local validate-corpus-stage-compatibility",
    "bijux-dna bench local render-corpus-skip-report",
    "bijux-dna bench local validate-taxonomy-database-fixture",
    "bijux-dna bench local judge-taxonomy-output",
    "bijux-dna bench local validate-slurm-dependencies",
    "bijux-dna bench local validate-slurm-shell-syntax",
    "bijux-dna bench local validate-slurm-script-bodies",
    "bijux-dna bench local render-slurm-submit-manifest",
    "bijux-dna bench local render-benchmark-summary",
    "bijux-dna bench local check-manifest-completion",
    "bijux-dna bench local check-output-completion",
    "bijux-dna bench local collect-runtime-metrics",
    "bijux-dna bench local render-tool-comparison-template",
    "bijux-dna bench local validate-stage-result",
    "bijux-dna bench local materialize-stage",
    "bijux-dna bench local fake-run-failures",
    "bijux-dna bench local fake-run-stages",
    "bijux-dna bench local render-slurm-scripts",
    "bijux-dna bench local render-stage-commands",
    "bijux-dna bench schema",
    "bijux-dna bench fastq trim-reads",
    "bijux-dna bench fastq trim-polyg-tails",
    "bijux-dna bench fastq trim-terminal-damage",
    "bijux-dna bench fastq validate-reads",
    "bijux-dna bench fastq detect-adapters",
    "bijux-dna bench fastq profile-read-lengths",
    "bijux-dna bench fastq filter",
    "bijux-dna bench fastq filter-low-complexity",
    "bijux-dna bench fastq merge",
    "bijux-dna bench fastq remove-duplicates",
    "bijux-dna bench fastq remove-chimeras",
    "bijux-dna bench fastq normalize-primers",
    "bijux-dna bench fastq infer-asvs",
    "bijux-dna bench fastq cluster-otus",
    "bijux-dna bench fastq normalize-abundance",
    "bijux-dna bench fastq correct",
    "bijux-dna bench fastq report-qc",
    "bijux-dna bench fastq umi",
    "bijux-dna bench fastq index-reference",
    "bijux-dna bench fastq screen-taxonomy",
    "bijux-dna bench fastq deplete-host",
    "bijux-dna bench fastq deplete-reference-contaminants",
    "bijux-dna bench fastq deplete-rrna",
    "bijux-dna bench fastq profile-reads",
    "bijux-dna bench fastq profile-overrepresented-sequences",
    "bijux-dna bench fastq preprocess",
    "bijux-dna bench bam stage",
    "bijux-dna bench bam pipeline",
    "bijux-dna ena select",
    "bijux-dna ena fetch",
    "bijux-dna tool validate",
    "bijux-dna domain validate",
    "bijux-dna domain coverage",
    "bijux-dna lab corpus list-fastq",
    "bijux-dna config init-hpc",
    "bijux-dna config doctor",
    "bijux-dna config campaign-preflight",
    "bijux-dna config campaign-dry-run",
    "bijux-dna config write-campaign-profiles",
    "bijux-dna slurm submit-stage-benchmark",
    "bijux-dna slurm submit-domain-benchmark",
    "bijux-dna slurm submit-cross-benchmark",
    "bijux-dna slurm submit-campaign",
    "bijux-dna slurm copy-back-manifest",
    "bijux-dna slurm verify-bundle",
    "bijux-dna slurm decrypt-bundle",
    "bijux-dna slurm rewrap-bundle",
    "bijux-dna slurm import-replay",
    "bijux-dna slurm import-campaign",
    "bijux-dna slurm export-failure-bundle",
    "bijux-dna slurm share-bundle",
    "bijux-dna slurm verify-results-policy",
    "bijux-dna bam run",
    "bijux-dna bam list-stages",
    "bijux-dna bam explain",
    "bijux-dna vcf plan",
    "bijux-dna vcf explain",
    "bijux-dna vcf run",
    "bijux-dna validate-manifests",
    "bijux-dna platform",
    "bijux-dna image-qa",
    "bijux-dna replay",
    "bijux-dna compare",
    "bijux-dna policies audit",
    "bijux-dna ci validate",
    "bijux-dna debug",
    "bijux-dna collect",
];

const REQUIRED_SECTIONS: &[&str] = &[
    "## Stable Operator Commands",
    "### Environment",
    "### Registry",
    "### Corpus",
    "### Status",
    "### FASTQ Run Surface",
    "### Pipeline Profiles",
    "### Analysis And Explanation",
    "### Benchmarking",
    "## Debug And Repository-Control Commands",
    "## Ownership Rules",
    "## Verification",
];

#[test]
fn command_doc_is_complete_cli_inventory() {
    let root = crate::support::crate_root("bijux-dna")
        .unwrap_or_else(|err| panic!("resolve crate root: {err}"));
    let commands_doc = root.join("docs/COMMANDS.md");
    let commands = std::fs::read_to_string(&commands_doc)
        .unwrap_or_else(|err| panic!("read {}: {err}", commands_doc.display()));

    assert!(
        commands.contains("This file is the single source of truth for commands managed by the `bijux-dna` crate."),
        "COMMANDS.md must identify itself as the CLI command SSOT"
    );
    for section in REQUIRED_SECTIONS {
        assert!(commands.contains(section), "COMMANDS.md must include `{section}`");
    }
    assert_eq!(
        documented_cli_commands(&commands),
        CLI_COMMANDS.iter().map(|command| (*command).to_string()).collect(),
        "docs/COMMANDS.md must list the exact CLI command inventory"
    );
    assert!(
        commands.contains("- `bijux-dna run validate` aliases `bijux-dna run validate-pre`."),
        "COMMANDS.md must document the visible validate alias"
    );
    assert!(
        commands.contains("- `bijux-dna run stats` aliases `bijux-dna run stats-neutral`."),
        "COMMANDS.md must document the visible stats alias"
    );
    assert!(
        commands.contains(
            "CARGO_TARGET_DIR=artifacts/cargo-target cargo test -p bijux-dna --test boundaries --no-default-features"
        ),
        "COMMANDS.md must list the focused command-inventory verification command"
    );
}

fn documented_cli_commands(commands: &str) -> BTreeSet<String> {
    commands
        .lines()
        .filter_map(|line| line.strip_prefix("- `"))
        .filter_map(|line| line.split_once('`').map(|(command, _)| command.to_string()))
        .filter(|command| command.starts_with("bijux-dna "))
        .collect()
}
