use bijux_dna_core::id_catalog;

use super::{contract, ObserverSpecializationContract};

pub(super) const CONTRACTS: &[ObserverSpecializationContract] = &[
    contract("fastq.filter_reads", id_catalog::TOOL_FASTP, "report_json"),
    contract("fastq.filter_reads", "seqkit", "report_json"),
    contract("fastq.filter_reads", "prinseq", "report_json"),
    contract("fastq.filter_reads", "bbduk", "report_json"),
    contract(
        "fastq.filter_low_complexity",
        "prinseq",
        "filter_report_json",
    ),
    contract("fastq.filter_low_complexity", "bbduk", "filter_report_json"),
    contract("fastq.deplete_rrna", "sortmerna", "rrna_report_json"),
    contract("fastq.deplete_host", "bowtie2", "host_depletion_report_json"),
    contract(
        "fastq.deplete_reference_contaminants",
        "bowtie2",
        "contaminant_screen_report_json",
    ),
    contract("fastq.extract_umis", "umi_tools", "report_json"),
    contract("fastq.merge_pairs", "adapterremoval", "report_json"),
    contract("fastq.merge_pairs", "pear", "report_json"),
    contract("fastq.merge_pairs", "vsearch", "report_json"),
    contract("fastq.merge_pairs", "bbmerge", "report_json"),
    contract("fastq.merge_pairs", "flash2", "report_json"),
    contract("fastq.merge_pairs", "leehom", "report_json"),
    contract("fastq.trim_reads", id_catalog::TOOL_FASTP, "report_json"),
    contract("fastq.trim_reads", id_catalog::TOOL_CUTADAPT, "report_json"),
    contract("fastq.trim_reads", "atropos", "report_json"),
    contract("fastq.trim_reads", "bbduk", "report_json"),
    contract("fastq.trim_reads", "adapterremoval", "report_json"),
    contract("fastq.trim_reads", "alientrimmer", "report_json"),
    contract("fastq.trim_reads", "trimmomatic", "report_json"),
    contract("fastq.trim_reads", "trim_galore", "report_json"),
    contract("fastq.trim_reads", "prinseq", "report_json"),
    contract("fastq.trim_reads", "seqkit", "report_json"),
    contract("fastq.trim_reads", "fastx_clipper", "report_json"),
    contract("fastq.trim_reads", "leehom", "report_json"),
    contract("fastq.trim_reads", "skewer", "report_json"),
    contract("fastq.trim_reads", "seqpurge", "report_json"),
    contract("fastq.remove_duplicates", "fastuniq", "report_json"),
    contract("fastq.remove_duplicates", "clumpify", "report_json"),
    contract("fastq.trim_terminal_damage", "adapterremoval", "report_json"),
    contract(
        "fastq.trim_terminal_damage",
        id_catalog::TOOL_CUTADAPT,
        "report_json",
    ),
    contract("fastq.trim_terminal_damage", "seqkit", "report_json"),
    contract("fastq.trim_polyg_tails", id_catalog::TOOL_FASTP, "report_json"),
    contract("fastq.trim_polyg_tails", "bbduk", "report_json"),
    contract("fastq.correct_errors", "rcorrector", "report_json"),
    contract("fastq.correct_errors", "musket", "report_json"),
    contract("fastq.correct_errors", "lighter", "report_json"),
    contract("fastq.correct_errors", "bayeshammer", "report_json"),
];
