[advisories]
unmaintained = "workspace"
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "allow"

[[bans.skip]]
name = "hashbrown"

[[bans.skip]]
name = "linux-raw-sys"

[[bans.skip]]
name = "rustix"

[[bans.skip]]
name = "thiserror"

[[bans.skip]]
name = "thiserror-impl"

[[bans.skip]]
name = "windows-sys"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
