[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "Zlib",
  "MPL-2.0",
]
deny = ["GPL-3.0", "AGPL-3.0"]
copyleft = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
