//! Owner: bijux-analyze
//! FASTQ schema versions.

pub const FASTQ_TRIM_SCHEMA_VERSION: i32 = 2;
pub const FASTQ_VALIDATE_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_FILTER_SCHEMA_VERSION: i32 = 2;
pub const FASTQ_MERGE_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_CORRECT_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_QC_POST_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_UMI_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_SCREEN_SCHEMA_VERSION: i32 = 1;
pub const FASTQ_STATS_SCHEMA_VERSION: i32 = 1;
