pub use crate::stages::ids::{
    bench_dir_name, STAGES, STAGE_CORRECT_ERRORS, STAGE_DETECT_ADAPTERS, STAGE_FILTER_READS, STAGE_MERGE_PAIRS,
    STAGE_PREFIX, STAGE_REPORT_QC, STAGE_DEPLETE_RRNA, STAGE_SCREEN_TAXONOMY, STAGE_PROFILE_READS,
    STAGE_TRIM_READS, STAGE_EXTRACT_UMIS, STAGE_VALIDATE_READS,
};
