# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# kraken2 Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.version="${TOOL_VERSION}"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_KRAKEN2=2.1.3
ENV VERSION_KRAKEN2=${VERSION_KRAKEN2}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget ca-certificates build-essential zlib1g-dev && \
    wget -q https://github.com/DerrickWood/kraken2/archive/v${VERSION_KRAKEN2}.tar.gz -O /tmp/kraken2.tar.gz && \
    tar -xzf /tmp/kraken2.tar.gz -C /opt && \
    cd /opt/kraken2-${VERSION_KRAKEN2} && \
    ./install_kraken2.sh /usr/local/bin && \
    rm -rf /tmp/kraken2.tar.gz /opt/kraken2-${VERSION_KRAKEN2} && \
    apt-get purge -y wget build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "kraken2 \"$@\""]
CMD []
