# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# seqpurge Dockerfile (ARM64)
# License: Apache-2.0

# Stage 1: Build ngs-bits core + SeqPurge
FROM ubuntu:24.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive
ARG SEQPURGE_VERSION=2025_05

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    qtbase5-dev \
    qt5-qmake \
    libqt5xmlpatterns5-dev \
    libqt5charts5-dev \
    libqt5svg5-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libhts-dev \
    libxml2-dev \
    pkg-config \
    git \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone --recursive --depth 1 --branch ${SEQPURGE_VERSION} \
        https://github.com/imgag/ngs-bits.git

WORKDIR /opt/ngs-bits

ENV SKIP_TESTS=1
RUN make build_libs_release -j$(nproc) SKIP_TESTS=1 && \
    make build_tools_release -j$(nproc) TOOLS=SeqPurge SKIP_TESTS=1

# sanity check
RUN test -x bin/SeqPurge

# Stage 2: Runtime image
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    libqt5core5a \
    libqt5xml5 \
    libqt5xmlpatterns5 \
    libqt5charts5 \
    libqt5svg5 \
    libqt5sql5 \
    libqt5sql5-sqlite \
    libxml2 \
    zlib1g \
    libbz2-1.0 \
    liblzma5 \
    libhts3 \
    libgomp1 \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/ngs-bits/bin/SeqPurge /usr/local/bin/seqpurge
COPY --from=builder /opt/ngs-bits/bin/*.so* /usr/local/lib/
RUN ldconfig

WORKDIR /data

ENTRYPOINT ["/usr/local/bin/seqpurge"]
CMD ["--help"]
