# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# flash2 Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_FLASH2=2.2.00
ENV VERSION_FLASH2=${VERSION_FLASH2}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential zlib1g-dev git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/dstreett/FLASH2.git /opt/FLASH2 && \
    cd /opt/FLASH2 && \
    git checkout tags/${VERSION_FLASH2} -b build-branch

RUN cd /opt/FLASH2 && \
    make -j"$(nproc)" && \
    cp flash2 /usr/local/bin/flash2 && \
    rm -rf /opt/FLASH2

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "flash2 \"$@\""]
CMD []
