# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Bijan Mousavi
#
# Container definition license: MIT.
# The bijux-dna software source code is licensed under Apache-2.0.
# VERSION_SOURCE: containers/versions/versions.toml
FROM quay.io/biocontainers/bcftools:1.20--h8b25389_0@sha256:badc3a0c7af72a83e5761ab0e881aa84204694bdead003b47552cb283958f78d
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=1.20
ARG OCI_UPSTREAM="https://github.com/samtools/bcftools"
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-genomics" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.version="${TOOL_VERSION}" \
      org.opencontainers.image.upstream="${OCI_UPSTREAM}"
LABEL org.opencontainers.image.tool="bcftools"
LABEL org.opencontainers.image.title="bcftools"
LABEL org.opencontainers.image.base.name="quay.io/biocontainers/bcftools:1.20--h8b25389_0@sha256:badc3a0c7af72a83e5761ab0e881aa84204694bdead003b47552cb283958f78d"
LABEL org.opencontainers.image.base.digest="sha256:badc3a0c7af72a83e5761ab0e881aa84204694bdead003b47552cb283958f78d"

ENTRYPOINT ["bcftools"]
CMD ["--help"]
