# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Bijan Mousavi
#
# Container definition license: GPL-3.0.
# The bijux-dna software source code is licensed under Apache-2.0.
FROM ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.version="${TOOL_VERSION}"
LABEL org.opencontainers.image.tool="kraken2"
LABEL org.opencontainers.image.base.name="ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
LABEL org.opencontainers.image.base.digest="sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_KRAKEN2=2.1.3
ENV VERSION_KRAKEN2=${VERSION_KRAKEN2}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget ca-certificates build-essential zlib1g-dev && \
    wget -q https://github.com/DerrickWood/kraken2/archive/v${VERSION_KRAKEN2}.tar.gz -O /tmp/kraken2.tar.gz && \
    tar -xzf /tmp/kraken2.tar.gz -C /opt && \
    cd /opt/kraken2-${VERSION_KRAKEN2} && \
    ./install_kraken2.sh /usr/local/bin && \
    rm -rf /tmp/kraken2.tar.gz /opt/kraken2-${VERSION_KRAKEN2} && \
    apt-get purge -y wget build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "kraken2 \"$@\""]
CMD []
