# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Bijan Mousavi
#
# Container definition license: GPL-3.0.
# The bijux-dna software source code is licensed under Apache-2.0.
# VERSION_SOURCE: containers/versions/versions.toml
FROM ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b AS builder
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=latest-pinned
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-genomics" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.version="${TOOL_VERSION}"
LABEL org.opencontainers.image.tool="skewer"
LABEL org.opencontainers.image.title="skewer"
LABEL org.opencontainers.image.base.name="ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
LABEL org.opencontainers.image.base.digest="sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
ARG TOOL_VERSION
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get install -y --no-install-recommends git=1:2.43.0-1ubuntu7.3 build-essential=12.10ubuntu1 zlib1g-dev=1:1.3.dfsg-3.1ubuntu2.1 ca-certificates=20240203 && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/relipmoc/skewer.git /opt/skewer && \
    cd /opt/skewer && git checkout 978e8e46cba44595ece623e5387749284a86b74b && \
    sed -i 's/bool operator()(const ELEMENT &elem1, const ELEMENT &elem2){/bool operator()(const ELEMENT \&elem1, const ELEMENT \&elem2) const {/' src/matrix.h && \
    make -j"$(nproc)"
FROM ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get install -y --no-install-recommends zlib1g=1:1.3.dfsg-3.1ubuntu2.1 ca-certificates=20240203 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /opt/skewer/skewer /usr/local/bin/skewer
ENTRYPOINT ["/usr/local/bin/skewer"]
CMD ["--help"]
