# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# metaphlan Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04

ARG VERSION_METAPHLAN=4.1.1
ENV VERSION_METAPHLAN=${VERSION_METAPHLAN} \
    DEBIAN_FRONTEND=noninteractive

# 1) OS‐level build deps for pysam, h5py, biopython, etc.
RUN set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      python3 \
      python3-pip \
      python3-dev \
      build-essential \
      pkg-config \
      libbz2-dev \
      liblzma-dev \
      libcurl4-gnutls-dev \
      libssl-dev \
      zlib1g-dev \
      libhdf5-dev && \
    rm -rf /var/lib/apt/lists/*

# 2) Install MetaPhlAn and its Python deps from PyPI
RUN set -eux; \
    pip3 install --no-cache-dir --break-system-packages metaphlan==${VERSION_METAPHLAN}

# 3) Rename the real script, leave a thin wrapper at `metaphlan`
RUN set -eux; \
    mv /usr/local/bin/metaphlan /usr/local/bin/metaphlan-bin && \
    printf '%s\n' \
      '#!/bin/sh' \
      'case "$1" in' \
      '  --version) echo "${VERSION_METAPHLAN}"; exit 0;;' \
      '  --help)    exec /usr/local/bin/metaphlan-bin --help;;' \
      '  *)         exec /usr/local/bin/metaphlan-bin "$@";; esac' \
      > /usr/local/bin/metaphlan && \
    chmod +x /usr/local/bin/metaphlan

WORKDIR /data
ENTRYPOINT ["metaphlan"]
CMD ["--help"]
