# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# seqtk Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_SEQTK=1.5-r133
ENV VERSION_SEQTK=${VERSION_SEQTK}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        ca-certificates \
        build-essential \
        zlib1g-dev && \
    git clone https://github.com/lh3/seqtk.git /opt/seqtk && \
    cd /opt/seqtk && \
    make && \
    mv seqtk /usr/local/bin/seqtk-bin && \
    rm -rf /opt/seqtk /var/lib/apt/lists/* && \
    apt-get purge -y git build-essential && \
    apt-get autoremove -y

# Create a wrapper script for unified Seqtk execution
RUN echo '#!/bin/sh' > /usr/local/bin/seqtk && \
    echo 'if [ "$1" = "--version" ]; then' >> /usr/local/bin/seqtk && \
    echo '    echo "$VERSION_SEQTK"' >> /usr/local/bin/seqtk && \
    echo '    exit 0' >> /usr/local/bin/seqtk && \
    echo 'elif [ "$1" = "--help" ]; then' >> /usr/local/bin/seqtk && \
    echo '    /usr/local/bin/seqtk-bin --help' >> /usr/local/bin/seqtk && \
    echo '    exit 0' >> /usr/local/bin/seqtk && \
    echo 'else' >> /usr/local/bin/seqtk && \
    echo '    /usr/local/bin/seqtk-bin "$@"' >> /usr/local/bin/seqtk && \
    echo 'fi' >> /usr/local/bin/seqtk && \
    chmod +x /usr/local/bin/seqtk

WORKDIR /data
CMD ["seqtk", "--help"]
