# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# prinseq Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04

ARG VERSION_PRINSEQ=1.2.4
ENV VERSION_PRINSEQ=${VERSION_PRINSEQ}
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "tzdata tzdata/Areas select Etc" > /tmp/tzdata.preseed && \
    echo "tzdata tzdata/Zones/Etc select UTC" >> /tmp/tzdata.preseed && \
    debconf-set-selections /tmp/tzdata.preseed && \
    rm /tmp/tzdata.preseed

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        autoconf \
        automake \
        libtool \
        wget \
        ca-certificates \
        pkg-config \
        m4 \
        libboost-all-dev \
        git \
        gzip \
    && rm -rf /var/lib/apt/lists/*

RUN for i in 1 2 3; do \
        git clone https://github.com/Adrian-Cantu/PRINSEQ-plus-plus.git /opt/prinseq && break || \
        echo "Git clone attempt $i failed, retrying..." && sleep 5; \
    done || { echo "Failed to clone PRINSEQ++ repository after 3 attempts"; exit 1; }

RUN cd /opt/prinseq && \
    touch NEWS README AUTHORS ChangeLog || true

RUN cd /opt/prinseq && \
    ls -l && \
    [ -f autogen.sh ] && echo "autogen.sh exists" || { echo "autogen.sh not found!"; exit 1; } && \
    set -ex && ./autogen.sh 2>&1 | tee /tmp/autogen_output.log && \
    cat /tmp/autogen_output.log && \
    [ $? -eq 0 ] || { echo "autogen.sh failed, see /tmp/autogen_output.log"; exit 1; }

RUN cd /opt/prinseq && \
    ./configure && \
    make -j$(nproc) && \
    make install

RUN apt-get remove -y git wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /opt/prinseq /tmp/autogen_output.log

ENV PATH="/usr/local/bin:$PATH"
WORKDIR /data
