# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# bbduk Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.version="${TOOL_VERSION}"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_BBDUK=39.08
ENV VERSION_BBDUK=${VERSION_BBDUK}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget ca-certificates openjdk-17-jre-headless && \
    wget -q https://sourceforge.net/projects/bbmap/files/BBMap_${VERSION_BBDUK}.tar.gz -O /tmp/bbmap.tar.gz && \
    tar -xzf /tmp/bbmap.tar.gz -C /opt && \
    rm /tmp/bbmap.tar.gz && \
    apt-get purge -y wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Create a wrapper script for unified BBDuk execution
RUN echo '#!/bin/sh' > /usr/local/bin/bbduk && \
    echo '/opt/bbmap/bbduk.sh "$@"' >> /usr/local/bin/bbduk && \
    chmod +x /usr/local/bin/bbduk

WORKDIR /data
ENTRYPOINT ["bbduk"]
CMD ["--help"]
