# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Bijan Mousavi
#
# Container definition license: GPL-3.0.
# The bijux-dna software source code is licensed under Apache-2.0.
# VERSION_SOURCE: containers/versions/versions.toml
FROM ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.version="${TOOL_VERSION}"
LABEL org.opencontainers.image.tool="flash2"
LABEL org.opencontainers.image.title="flash2"
LABEL org.opencontainers.image.base.name="ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
LABEL org.opencontainers.image.base.digest="sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_FLASH2=2.2.00
ENV VERSION_FLASH2=${VERSION_FLASH2}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential zlib1g-dev git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/dstreett/FLASH2.git /opt/FLASH2 && \
    cd /opt/FLASH2 && \
    git checkout 64826f4574b11b3c0ae7460826f30be16f49c3ea

RUN cd /opt/FLASH2 && \
    make -j"$(nproc)" && \
    cp flash2 /usr/local/bin/flash2 && \
    rm -rf /opt/FLASH2

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "flash2 \"$@\""]
CMD []
