# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Bijan Mousavi
#
# Container definition license: GPL-3.0.
# The bijux-dna software source code is licensed under Apache-2.0.
# VERSION_SOURCE: containers/versions/versions.toml
FROM ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=0.3.11
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-genomics"       org.opencontainers.image.revision="${OCI_REVISION}"       org.opencontainers.image.created="${OCI_CREATED}"       org.opencontainers.image.licenses="GPL-3.0"       org.opencontainers.image.version="${TOOL_VERSION}"
LABEL org.opencontainers.image.tool="mosdepth"
LABEL org.opencontainers.image.title="mosdepth"
LABEL org.opencontainers.image.base.name="ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
LABEL org.opencontainers.image.base.digest="sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -y --no-install-recommends     ca-certificates=20240203 mosdepth=0.3.6+ds-1 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/env", "mosdepth"]
CMD ["--help"]
