# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# trim_galore Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_TRIM_GALORE=0.6.10
ENV TRIM_GALORE=${VERSION_TRIM_GALORE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev build-essential fastqc wget && \
    rm -rf /var/lib/apt/lists/*


RUN wget -q https://github.com/FelixKrueger/TrimGalore/archive/${VERSION_TRIM_GALORE}.tar.gz \
    -O /tmp/trimgalore.tar.gz && \
    tar -xzf /tmp/trimgalore.tar.gz -C /opt && \
    ln -sf /opt/TrimGalore-${VERSION_TRIM_GALORE}/trim_galore /usr/local/bin/trim_galore && \
    chmod +x /usr/local/bin/trim_galore && \
    rm /tmp/trimgalore.tar.gz

RUN pip3 install --no-cache-dir --break-system-packages cutadapt

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "trim_galore \"$@\""]
CMD []
