# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# fastp Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_FASTP=0.23.4
ENV VERSION_FASTP=${VERSION_FASTP}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget ca-certificates build-essential zlib1g-dev libdeflate-dev libisal-dev && \
    wget -q https://github.com/OpenGene/fastp/archive/v${VERSION_FASTP}.tar.gz -O /tmp/fastp.tar.gz && \
    tar -xzf /tmp/fastp.tar.gz -C /opt && \
    cd /opt/fastp-${VERSION_FASTP} && \
    make && \
    cp fastp /usr/local/bin/ && \
    rm -rf /tmp/fastp.tar.gz /opt/fastp-${VERSION_FASTP} && \
    apt-get purge -y wget build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "fastp \"$@\""]
CMD []
