# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# samtools Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_SAMTOOLS=1.21
ENV VERSION_SAMTOOLS=${VERSION_SAMTOOLS}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        samtools && \
    mv /usr/bin/samtools /usr/local/bin/samtools-bin && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y

# Create a wrapper script for unified Samtools execution
RUN echo '#!/bin/sh' > /usr/local/bin/samtools && \
    echo 'if [ "$1" = "--version" ]; then' >> /usr/local/bin/samtools && \
    echo '    echo "$VERSION_SAMTOOLS"' >> /usr/local/bin/samtools && \
    echo '    exit 0' >> /usr/local/bin/samtools && \
    echo 'elif [ "$1" = "--help" ]; then' >> /usr/local/bin/samtools && \
    echo '    /usr/local/bin/samtools-bin --help' >> /usr/local/bin/samtools && \
    echo '    exit 0' >> /usr/local/bin/samtools && \
    echo 'else' >> /usr/local/bin/samtools && \
    echo '    /usr/local/bin/samtools-bin "$@"' >> /usr/local/bin/samtools && \
    echo 'fi' >> /usr/local/bin/samtools && \
    chmod +x /usr/local/bin/samtools

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "samtools \"$@\""]
CMD ["--help"]
