# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# fastqvalidator_official Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04 AS builder
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.version="${TOOL_VERSION}"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_FASTQVALIDATOR=v0.1.1
ENV VERSION_FASTQVALIDATOR=${VERSION_FASTQVALIDATOR}

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        git \
        build-essential \
        zlib1g-dev \
        libbz2-dev \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/statgen/libStatGen.git /opt/libStatGen && \
    git clone --branch "${VERSION_FASTQVALIDATOR}" --depth 1 \
        https://github.com/statgen/fastQValidator.git /opt/fastQValidator

WORKDIR /opt/fastQValidator

RUN make -j"$(nproc)" LIB_PATH_FASTQ_VALIDATOR=/opt/libStatGen && \
    make install PREFIX=/usr/local

FROM ubuntu:24.04
ARG VERSION_FASTQVALIDATOR=v0.1.1
ENV VERSION_FASTQVALIDATOR=${VERSION_FASTQVALIDATOR}

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        zlib1g \
        libbz2-1.0 \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/fastQValidator /usr/local/bin/fq-validator-bin

RUN printf '%s\n' \
    '#!/bin/sh' \
    'case "$1" in' \
    '  --version) echo "${VERSION_FASTQVALIDATOR#v}"; exit 0;;' \
    '  --help|-h|"") exec /usr/local/bin/fq-validator-bin --help;;' \
    '  *) exec /usr/local/bin/fq-validator-bin "$@";; esac' \
  > /usr/local/bin/fastq-validator && \
  chmod +x /usr/local/bin/fastq-validator

WORKDIR /data

LABEL org.opencontainers.image.source="https://github.com/statgen/fastQValidator" \
      org.opencontainers.image.version="${VERSION_FASTQVALIDATOR}"

CMD ["fastq-validator", "--help"]
