# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# musket Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ARG OCI_REVISION=unknown
ARG OCI_CREATED=unknown
ARG TOOL_VERSION=unknown
LABEL org.opencontainers.image.source="https://github.com/bijux/bijux-dna" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.version="${TOOL_VERSION}"
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION_MUSKET=1.1
ENV VERSION_MUSKET=${VERSION_MUSKET}

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends --no-install-suggests -o Acquire::Retries=3 \
        wget \
        ca-certificates \
        build-essential \
        zlib1g-dev \
        libgomp1 && \
    wget -q https://sourceforge.net/projects/musket/files/musket-${VERSION_MUSKET}.tar.gz/download -O /tmp/musket.tar.gz && \
    tar -xzf /tmp/musket.tar.gz -C /opt && \
    cd /opt/musket-${VERSION_MUSKET} && \
    make && \
    mv musket /usr/local/bin/musket-bin && \
    rm -rf /tmp/musket.tar.gz /opt/musket-${VERSION_MUSKET} /var/lib/apt/lists/* && \
    apt-get purge -y wget ca-certificates build-essential zlib1g-dev && \
    apt-get autoremove -y

# Create a wrapper script for unified Musket execution
RUN echo '#!/bin/sh' > /usr/local/bin/musket && \
    echo 'if [ "$1" = "--version" ]; then' >> /usr/local/bin/musket && \
    echo '    echo "$VERSION_MUSKET"' >> /usr/local/bin/musket && \
    echo '    exit 0' >> /usr/local/bin/musket && \
    echo 'elif [ "$1" = "--help" ]; then' >> /usr/local/bin/musket && \
    echo '    /usr/local/bin/musket-bin --help' >> /usr/local/bin/musket && \
    echo '    exit 0' >> /usr/local/bin/musket && \
    echo 'else' >> /usr/local/bin/musket && \
    echo '    /usr/local/bin/musket-bin "$@"' >> /usr/local/bin/musket && \
    echo 'fi' >> /usr/local/bin/musket && \
    chmod +x /usr/local/bin/musket

WORKDIR /data
ENTRYPOINT ["/bin/sh", "-c", "musket \"$@\""]
CMD ["--help"]
