# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bijan Mousavi
#
# This file is part of bijux-dna.
#
# bijux-dna is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bijux-dna is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bijux-dna. If not, see <https://www.gnu.org/licenses/>.
# fastq_screen Dockerfile (ARM64)
# License: Apache-2.0
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
ARG VERSION_FASTQ_SCREEN=0.15.3
ENV VERSION_FASTQ_SCREEN=${VERSION_FASTQ_SCREEN}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update -qq -o Acquire::Retries=5 -o Acquire::http::Timeout=30 && \
    apt-get install -y --no-install-recommends \
        perl \
        curl \
        ca-certificates \
        bzip2 \
        gzip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN curl -fsSL -o fastq_screen.tar.gz "https://github.com/StevenWingett/FastQ-Screen/archive/refs/tags/v${VERSION_FASTQ_SCREEN}.tar.gz" && \
    tar -xzf fastq_screen.tar.gz && \
    mv FastQ-Screen-${VERSION_FASTQ_SCREEN} fastq_screen && \
    ln -s /opt/fastq_screen/fastq_screen /usr/local/bin/fastq_screen

WORKDIR /data

LABEL org.opencontainers.image.source="https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/" \
      org.opencontainers.image.version="${VERSION_FASTQ_SCREEN}"

CMD ["fastq_screen", "--help"]
