pub const METRIC_REGISTRY_CORE: [MetricSpec; 15] = [
    MetricSpec {
        id: MetricId::RuntimeS,
        name: "runtime_s",
        meaning: "Wall-clock runtime in seconds",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MemoryMb,
        name: "memory_mb",
        meaning: "Peak container memory usage in MB",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ExitCode,
        name: "exit_code",
        meaning: "Exit code from tool execution",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsIn,
        name: "reads_in",
        meaning: "Number of input reads",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
            "fastq.stats_neutral",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsOut,
        name: "reads_out",
        meaning: "Number of output reads",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsDropped,
        name: "reads_dropped",
        meaning: "Number of reads dropped during filtering",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedByN,
        name: "reads_removed_by_n",
        meaning: "Reads removed due to N content",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedByEntropy,
        name: "reads_removed_by_entropy",
        meaning: "Reads removed due to low entropy",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedLowComplexity,
        name: "reads_removed_low_complexity",
        meaning: "Reads removed due to low complexity",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedByKmer,
        name: "reads_removed_by_kmer",
        meaning: "Reads removed due to k-mer matching",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedContaminantKmer,
        name: "reads_removed_contaminant_kmer",
        meaning: "Reads removed due to contaminant k-mer matching",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsRemovedByLength,
        name: "reads_removed_by_length",
        meaning: "Reads removed due to length filtering",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.filter"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsTotal,
        name: "reads_total",
        meaning: "Total reads for validation",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.validate_pre", "fastq.stats_neutral"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsValid,
        name: "reads_valid",
        meaning: "Reads that pass validation",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.validate_pre"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsInvalid,
        name: "reads_invalid",
        meaning: "Reads that fail validation",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.validate_pre"],
        measured: true,
        derived: false,
    },
];
