pub const METRIC_REGISTRY_QUALITY: [MetricSpec; 15] = [
    MetricSpec {
        id: MetricId::BasesIn,
        name: "bases_in",
        meaning: "Number of input bases",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesOut,
        name: "bases_out",
        meaning: "Number of output bases",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesTotal,
        name: "bases_total",
        meaning: "Total bases for stats",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.stats_neutral"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairsIn,
        name: "pairs_in",
        meaning: "Number of input read pairs",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairsOut,
        name: "pairs_out",
        meaning: "Number of output read pairs",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim",
            "fastq.validate_pre",
            "fastq.filter",
            "fastq.merge",
            "fastq.correct",
            "fastq.qc_post",
            "fastq.umi",
            "fastq.screen",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsR1,
        name: "reads_r1",
        meaning: "Number of reads in R1",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsR2,
        name: "reads_r2",
        meaning: "Number of reads in R2",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsMerged,
        name: "reads_merged",
        meaning: "Number of merged reads",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsUnmerged,
        name: "reads_unmerged",
        meaning: "Number of unmerged reads",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQBefore,
        name: "mean_q_before",
        meaning: "Mean quality before processing",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &["fastq.trim", "fastq.filter", "fastq.correct"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQAfter,
        name: "mean_q_after",
        meaning: "Mean quality after processing",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &["fastq.trim", "fastq.filter", "fastq.correct"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQ,
        name: "mean_q",
        meaning: "Mean quality score",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &["fastq.validate_pre", "fastq.qc_post", "fastq.stats_neutral"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MergeRate,
        name: "merge_rate",
        meaning: "Merged reads / total reads",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.merge"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DedupRate,
        name: "dedup_rate",
        meaning: "Fraction of reads retained after deduplication",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.umi"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::KmerFixRate,
        name: "kmer_fix_rate",
        meaning: "Fraction of k-mers corrected",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.correct"],
        measured: true,
        derived: false,
    },
];
pub const METRIC_REGISTRY_FASTQ: [MetricSpec; 13] = [
    MetricSpec {
        id: MetricId::ContaminationRate,
        name: "contamination_rate",
        meaning: "Estimated contamination rate from screening",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen", "fastq.qc_post", "fastq.validate_pre"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminationSummary,
        name: "contamination_summary",
        meaning: "Structured contamination summary",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GcPercent,
        name: "gc_percent",
        meaning: "GC percent",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: 100.0,
        }),
        stages: &["fastq.stats_neutral"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::LengthHistogram,
        name: "length_histogram",
        meaning: "Read length histogram",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.stats_neutral"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DeltaMetrics,
        name: "delta_metrics",
        meaning: "Read/base retention deltas",
        direction: MetricDirection::HigherBetter,
        range: None,
        stages: &["fastq.trim", "fastq.filter", "fastq.correct"],
        measured: false,
        derived: true,
    },
    MetricSpec {
        id: MetricId::AdapterPreset,
        name: "adapter_preset",
        meaning: "Adapter preset identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankId,
        name: "adapter_bank_id",
        meaning: "Adapter bank identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankHash,
        name: "adapter_bank_hash",
        meaning: "Adapter bank hash",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterOverrides,
        name: "adapter_overrides",
        meaning: "Adapter override parameters",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcRawDir,
        name: "raw_fastqc_dir",
        meaning: "Raw FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.qc_post"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcTrimmedDir,
        name: "trimmed_fastqc_dir",
        meaning: "Trimmed FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.qc_post"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcReport,
        name: "multiqc_report",
        meaning: "MultiQC report path",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.qc_post"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcData,
        name: "multiqc_data",
        meaning: "MultiQC data directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.qc_post"],
        measured: true,
        derived: false,
    },
];

pub const DERIVED_METRIC_REGISTRY: [DerivedMetricSpec; 4] = [
    DerivedMetricSpec {
        id: DerivedMetricId::ReadRetention,
        name: "read_retention",
        meaning: "reads_out / reads_in",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.trim", "fastq.filter", "fastq.correct", "fastq.umi"],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::BaseRetention,
        name: "base_retention",
        meaning: "bases_out / bases_in",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.trim", "fastq.filter", "fastq.correct", "fastq.umi"],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::MergeEfficiency,
        name: "merge_efficiency",
        meaning: "reads_merged / (reads_merged + reads_unmerged)",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.merge"],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::ErrorReductionProxy,
        name: "error_reduction_proxy",
        meaning: "proxy for error reduction",
        direction: MetricDirection::HigherBetter,
        range: None,
        stages: &["fastq.correct"],
    },
];
use crate::aggregate::schema::defs::{
    DerivedMetricSpec, MetricDirection, MetricId, MetricRange, MetricSpec,
};
use bijux_core::prelude::DerivedMetricId;
