/// Canonical tool identifier for `samtools`.
pub const TOOL_SAMTOOLS: &str = "samtools";
/// Canonical tool identifier for `bwa`.
pub const TOOL_BWA: &str = "bwa";
/// Canonical tool identifier for `gatk`.
pub const TOOL_GATK: &str = "gatk";
/// Canonical tool identifier for `preseq`.
pub const TOOL_PRESEQ: &str = "preseq";
/// Canonical tool identifier for `mosdepth`.
pub const TOOL_MOSDEPTH: &str = "mosdepth";
/// Canonical tool identifier for `pydamage`.
pub const TOOL_PYDAMAGE: &str = "pydamage";
/// Canonical tool identifier for `authenticct`.
pub const TOOL_AUTHENTICCT: &str = "authenticct";
/// Canonical tool identifier for `pmdtools`.
pub const TOOL_PMDTOOLS: &str = "pmdtools";
/// Canonical tool identifier for `schmutzi`.
pub const TOOL_SCHMUTZI: &str = "schmutzi";
/// Canonical tool identifier for `verifybamid2`.
pub const TOOL_VERIFYBAMID2: &str = "verifybamid2";
/// Canonical tool identifier for `contammix`.
pub const TOOL_CONTAMMIX: &str = "contammix";
/// Canonical tool identifier for `rxy`.
pub const TOOL_RXY: &str = "rxy";
/// Canonical tool identifier for `angsd`.
pub const TOOL_ANGSD: &str = "angsd";
/// Canonical tool identifier for `yleaf`.
pub const TOOL_YLEAF: &str = "yleaf";
/// Canonical tool identifier for `king`.
pub const TOOL_KING: &str = "king";
