/// Canonical tool identifier for `fastqvalidator`.
pub const TOOL_FASTQVALIDATOR_OFFICIAL: &str = "fastqvalidator";
/// Canonical tool identifier for `seqkit_stats`.
pub const TOOL_SEQKIT_STATS: &str = "seqkit_stats";
/// Canonical tool identifier for `rcorrector`.
pub const TOOL_RCORRECTOR: &str = "rcorrector";
/// Canonical tool identifier for `umi_tools`.
pub const TOOL_UMI_TOOLS: &str = "umi_tools";
/// Canonical tool identifier for `fastqc`.
pub const TOOL_FASTQC: &str = "fastqc";
/// Canonical tool identifier for `fastp`.
pub const TOOL_FASTP: &str = "fastp";
/// Canonical tool identifier for `adapterremoval`.
pub const TOOL_ADAPTERREMOVAL: &str = "adapterremoval";
/// Canonical tool identifier for `cutadapt`.
pub const TOOL_CUTADAPT: &str = "cutadapt";
/// Canonical tool identifier for `pear`.
pub const TOOL_PEAR: &str = "pear";
/// Canonical tool identifier for `vsearch`.
pub const TOOL_VSEARCH: &str = "vsearch";
/// Canonical tool identifier for `leehom`.
pub const TOOL_LEEHOM: &str = "leehom";
/// Canonical tool identifier for `kraken2`.
pub const TOOL_KRAKEN2: &str = "kraken2";
/// Canonical tool identifier for `bbduk`.
pub const TOOL_BBDUK: &str = "bbduk";
/// Canonical tool identifier for `bowtie2`.
pub const TOOL_BOWTIE2: &str = "bowtie2";
/// Canonical tool identifier for `sortmerna`.
pub const TOOL_SORTMERNA: &str = "sortmerna";
/// Canonical tool identifier for `dada2`.
pub const TOOL_DADA2: &str = "dada2";
