use super::{
    artifact_env, artifact_env_with_common_test_env, run_native_ops_command, run_program_with_env,
    run_programs_with_env, tooling_benchmark_smoke_level1, tooling_ci_clippy_executors,
    NativeOpsCommandKey, OpsCommandOutcome, Result, Workspace,
};

pub(in super::super) fn tooling_cargo_targets(
    workspace: &Workspace,
    args: &[String],
) -> Result<OpsCommandOutcome> {
    let Some(subcommand) = args.first().map(String::as_str) else {
        return Ok(OpsCommandOutcome::failure(
            "Usage: cargo run -p bijux-dna-dev -- tooling run cargo-targets -- <subcommand> [args...]\n",
        ));
    };
    let envs = artifact_env(workspace)?;
    let common_envs = artifact_env_with_common_test_env(workspace)?;
    match subcommand {
        "policy-fast" => run_program_with_env(
            workspace,
            "cargo",
            &[
                "test".to_string(),
                "-p".to_string(),
                "bijux-dna-policies".to_string(),
                "--test".to_string(),
                "dependency_graph".to_string(),
                "--test".to_string(),
                "purity_scans".to_string(),
                "--test".to_string(),
                "core_layering".to_string(),
                "--test".to_string(),
                "domain_dependency_policy".to_string(),
                "--test".to_string(),
                "ci_tools_policy".to_string(),
                "--test".to_string(),
                "dev_deps_policy".to_string(),
                "--test".to_string(),
                "heavy_deps_policy".to_string(),
            ],
            &envs,
        ),
        "ssot-policy-fast" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "policy_test_names_are_consistent",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "supported_stages_and_tools_are_complete",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "each_tool_has_exactly_one_domain_and_stage_binding",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "test-profile-invariants" => run_program_with_env(
            workspace,
            "cargo",
            &[
                "test".to_string(),
                "-p".to_string(),
                "bijux-dna-pipelines".to_string(),
                "--test".to_string(),
                "invariant_fast".to_string(),
                "--".to_string(),
                "--nocapture".to_string(),
            ],
            &common_envs,
        ),
        "registry-lint" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "production_registry_is_pinned_and_non_floating",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "profiles_only_use_valid_production_tools",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "unit-contract-fast" => run_programs_with_env(
            workspace,
            &[
                ("cargo", vec!["test", "-p", "bijux-dna-runner", "--lib", "--", "--nocapture"]),
                (
                    "cargo",
                    vec!["test", "-p", "bijux-dna-planner-fastq", "--lib", "--", "--nocapture"],
                ),
                (
                    "cargo",
                    vec!["test", "-p", "bijux-dna-planner-bam", "--lib", "--", "--nocapture"],
                ),
                (
                    "cargo",
                    vec!["test", "-p", "bijux-dna-stages-fastq", "--lib", "--", "--nocapture"],
                ),
                ("cargo", vec!["test", "-p", "bijux-dna-stages-bam", "--lib", "--", "--nocapture"]),
                ("cargo", vec!["test", "-p", "bijux-dna-api", "--lib", "--", "--nocapture"]),
            ],
            &common_envs,
        ),
        "release-readiness" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "profiles_release_readiness_gate",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "reference_adna_profile_uses_production_tools_only",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "policy-full" => run_program_with_env(
            workspace,
            "cargo",
            &["test".to_string(), "-p".to_string(), "bijux-dna-policies".to_string()],
            &envs,
        ),
        "domain-coverage" => run_program_with_env(
            workspace,
            "cargo",
            &[
                "run".to_string(),
                "-p".to_string(),
                "bijux-dna".to_string(),
                "--bin".to_string(),
                "bijux-dna".to_string(),
                "--".to_string(),
                "domain".to_string(),
                "coverage".to_string(),
                "--domain-dir".to_string(),
                "domain".to_string(),
            ],
            &envs,
        ),
        "snapshots" => run_program_with_env(
            workspace,
            "cargo",
            &["insta".to_string(), "test".to_string(), "--workspace".to_string()],
            &envs,
        ),
        "snapshots-accept" => run_program_with_env(
            workspace,
            "cargo",
            &["insta".to_string(), "accept".to_string(), "--workspace".to_string()],
            &envs,
        ),
        "snapshots-review" => run_program_with_env(
            workspace,
            "cargo",
            &["insta".to_string(), "review".to_string()],
            &envs,
        ),
        "fix-snapshots" => run_programs_with_env(
            workspace,
            &[
                ("cargo", vec!["insta", "test", "--workspace"]),
                ("cargo", vec!["insta", "accept", "--workspace"]),
            ],
            &envs,
        ),
        "policy-only-fast-gate" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "--test",
                        "boundaries",
                        "--test",
                        "determinism",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-pipelines",
                        "--test",
                        "contracts",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-runtime",
                        "--test",
                        "contracts",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "essential-integrity" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "crate_responsibility_matrix_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "cargo_metadata_snapshot_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "policy_layer_split_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "public_api_stability_tiers_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "workflow_truth_boundary_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec!["run", "-q", "-p", "bijux-dna-dev", "--", "domain", "run", "validate"],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-stage-contract",
                        "--test",
                        "schemas",
                        "run_execution_plan_snapshot",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-planner-fastq",
                        "--test",
                        "contracts",
                        "stage_reasons_are_deterministic_for_new_fastq_stage_set",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-runtime",
                        "--test",
                        "contracts",
                        "run_layout_paths_match_contract",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "status_discovers_evidence_bundle_and_correlation",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "essential-execute" => run_programs_with_env(
            workspace,
            &[
                ("cargo", vec!["test", "-p", "bijux-dna-runner", "--lib", "--", "--nocapture"]),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "v1_dry_run_manifest",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "v1_status_evidence",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "schemas",
                        "v1_cross_api_stability",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "essential-evidence" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-analyze",
                        "--test",
                        "contracts",
                        "evidence_bundle_builds_and_verifies",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "v1_dry_run_manifest",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "v1_status_evidence",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-planner-bam",
                        "--test",
                        "contracts",
                        "planner_manifest_contract",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-planner-vcf",
                        "--test",
                        "contracts",
                        "vcf_",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        ),
        "essential-compatibility" => run_programs_with_env(
            workspace,
            &[
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "schema_registry_covers_governed_iteration_contracts",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "workflow_manifest_v0_upgrades_deterministically",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "plan_manifest_v0_upgrade_preserves_equivalent_v1_fingerprint",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "fixture_backed_legacy_plan_explains_expected_fingerprint_change",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "api_route_adapters_link_v1_routes_to_governed_schema_families",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-core",
                        "--test",
                        "contracts",
                        "error_registry_covers_governed_categories_with_remediation",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-runtime",
                        "--test",
                        "contracts",
                        "legacy_artifact_inventory_is_upgraded_with_audit",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-runtime",
                        "--test",
                        "contracts",
                        "artifact_inventory_reader_accepts_supported_legacy_fixture",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-analyze",
                        "--test",
                        "contracts",
                        "evidence_bundle_builds_and_verifies",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-analyze",
                        "--test",
                        "contracts",
                        "draft_profile_tolerates_missing_publication_material",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "route_inventory_exposes_governed_v1_adapters",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "plan_response_adapter_surfaces_workflow_and_plan_models",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "execute_and_status_adapters_match_runtime_and_evidence_fields",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "contracts",
                        "dry_run_adapter_declares_runtime_and_evidence_outputs",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-api",
                        "--test",
                        "schemas",
                        "route_version_inventory_schema_is_stable",
                        "--",
                        "--nocapture",
                    ],
                ),
                (
                    "cargo",
                    vec![
                        "test",
                        "-p",
                        "bijux-dna-policies",
                        "--test",
                        "contracts",
                        "compatibility_reference_policy",
                        "--",
                        "--nocapture",
                    ],
                ),
            ],
            &common_envs,
        )
        .and_then(|outcome| {
            if outcome.is_success() {
                run_native_ops_command(NativeOpsCommandKey::DocsCheckGeneratedDocs, workspace, &[])
            } else {
                Ok(outcome)
            }
        }),
        "essential-release" => {
            let integrity =
                tooling_cargo_targets(workspace, &[String::from("essential-integrity")])?;
            if !integrity.is_success() {
                return Ok(integrity);
            }
            let compatibility =
                tooling_cargo_targets(workspace, &[String::from("essential-compatibility")])?;
            if !compatibility.is_success() {
                return Ok(compatibility);
            }
            let benchmark = tooling_benchmark_smoke_level1(workspace, &[])?;
            if !benchmark.is_success() {
                return Ok(benchmark);
            }
            run_programs_with_env(
                workspace,
                &[
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-analyze",
                            "--test",
                            "contracts",
                            "evidence_bundle_builds_and_verifies",
                            "--",
                            "--nocapture",
                        ],
                    ),
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-api",
                            "--test",
                            "contracts",
                            "status_discovers_evidence_bundle_and_correlation",
                            "--",
                            "--nocapture",
                        ],
                    ),
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-api",
                            "--test",
                            "contracts",
                            "dry_run_emits_manifest_and_graph_without_execution",
                            "--",
                            "--nocapture",
                        ],
                    ),
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-api",
                            "--test",
                            "contracts",
                            "execute_simulation_writes_governed_runtime_contracts_without_process_execution",
                            "--",
                            "--nocapture",
                        ],
                    ),
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-stage-contract",
                            "--lib",
                            "evaluate_stage_admission_returns_stable_refusal_codes",
                            "--",
                            "--nocapture",
                        ],
                    ),
                    (
                        "cargo",
                        vec![
                            "test",
                            "-p",
                            "bijux-dna-policies",
                            "--test",
                            "contracts",
                            "refusal_bundle_policy",
                            "--",
                            "--nocapture",
                        ],
                    ),
                ],
                &common_envs,
            )
        }
        "vcf-certification" => run_program_with_env(
            workspace,
            "cargo",
            &[
                "nextest".to_string(),
                "run".to_string(),
                "-p".to_string(),
                "bijux-dna-stages-vcf".to_string(),
                "--all-features".to_string(),
                "--failure-output".to_string(),
                "immediate-final".to_string(),
                "--no-tests".to_string(),
                "pass".to_string(),
            ],
            &common_envs,
        ),
        "ci-clippy-executors" => tooling_ci_clippy_executors(workspace, &[]),
        "nextest-run" => run_program_with_env(
            workspace,
            "cargo",
            &std::iter::once("nextest".to_string())
                .chain(std::iter::once("run".to_string()))
                .chain(args.iter().skip(1).cloned())
                .collect::<Vec<_>>(),
            &common_envs,
        ),
        "bam-smoke-test" => run_program_with_env(
            workspace,
            "cargo",
            &[
                "test".to_string(),
                "-p".to_string(),
                "bijux-dna-api".to_string(),
                "bam_smoke_runner_minimal_pipeline_validates_report_section_presence".to_string(),
                "--".to_string(),
                "--exact".to_string(),
            ],
            &common_envs,
        ),
        other => Ok(OpsCommandOutcome::failure(format!(
            "unsupported cargo-targets subcommand: {other}\n"
        ))),
    }
}
