use crate::aggregate::schema::defs::{MetricDirection, MetricId, MetricRange, MetricSpec};
pub const METRIC_REGISTRY_PROCESSING_AND_VALIDATION: [MetricSpec; 56] = [
    MetricSpec {
        id: MetricId::CandidateAdapterCount,
        name: "candidate_adapter_count",
        meaning: "Number of candidate adapters reported by the governed observer",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterTrimmedFraction,
        name: "adapter_trimmed_fraction",
        meaning: "Fraction of reads with adapter evidence when the backend can estimate it",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DetectionConfidence,
        name: "detection_confidence",
        meaning: "Highest governed per-adapter support fraction among detected adapter identities",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DetectionThreshold,
        name: "detection_threshold",
        meaning: "Minimum governed support fraction required to admit an adapter identity",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PrimerTrimmedFraction,
        name: "primer_trimmed_fraction",
        meaning: "Fraction of reads that required governed primer trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.normalize_primers"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::OrientationForwardFraction,
        name: "orientation_forward_fraction",
        meaning: "Fraction of reads reported in the governed forward orientation",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.normalize_primers"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DeltaMetrics,
        name: "delta_metrics",
        meaning: "Read/base retention deltas",
        direction: MetricDirection::HigherBetter,
        range: None,
        stages: &["fastq.trim_reads", "fastq.filter_reads", "fastq.correct_errors"],
        measured: false,
        derived: true,
    },
    MetricSpec {
        id: MetricId::PairedMode,
        name: "paired_mode",
        meaning: "Observed read layout during execution",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.trim_reads",
            "fastq.trim_polyg_tails",
            "fastq.remove_duplicates",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Tool,
        name: "tool",
        meaning: "Resolved tool identifier for the stage observation",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Threads,
        name: "threads",
        meaning: "Resolved thread count used by stage execution",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterPolicy,
        name: "adapter_policy",
        meaning: "Resolved adapter handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxPolicy,
        name: "polyx_policy",
        meaning: "Resolved polyX handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::NPolicy,
        name: "n_policy",
        meaning: "Resolved ambiguous-base handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminantPolicy,
        name: "contaminant_policy",
        meaning: "Resolved contaminant handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RawBackendReportFormat,
        name: "raw_backend_report_format",
        meaning: "Backend-native report format emitted by the stage",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads", "fastq.trim_polyg_tails", "fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DedupRate,
        name: "dedup_rate",
        meaning: "Fraction of input reads removed by duplicate filtering",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DedupMode,
        name: "dedup_mode",
        meaning: "Resolved duplicate-removal policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::KeepOrder,
        name: "keep_order",
        meaning: "Whether duplicate removal preserves input order",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateReads,
        name: "duplicates_removed",
        meaning: "Number of reads removed as duplicates",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateClassCount,
        name: "duplicate_class_count",
        meaning: "Number of duplicate classes represented in the governed summary",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateProvenanceJson,
        name: "duplicate_provenance_json",
        meaning: "Path to the governed duplicate provenance artifact",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterPreset,
        name: "adapter_preset",
        meaning: "Adapter preset identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankId,
        name: "adapter_bank_id",
        meaning: "Adapter bank identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankHash,
        name: "adapter_bank_hash",
        meaning: "Adapter bank hash",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterOverrides,
        name: "adapter_overrides",
        meaning: "Adapter override parameters",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterReport,
        name: "adapter_report",
        meaning: "Path to the governed adapter-detection report artifact",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DetectedAdapterIds,
        name: "detected_adapter_ids",
        meaning: "Governed adapter-bank identifiers admitted by adapter detection",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ValidatedInputs,
        name: "validated_inputs",
        meaning: "Number of FASTQ inputs validated",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ValidatedPairs,
        name: "validated_pairs",
        meaning: "Number of read pairs validated",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairSyncChecked,
        name: "pair_sync_checked",
        meaning: "Whether pair synchronization was evaluated",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairSyncPass,
        name: "pair_sync_pass",
        meaning: "Whether pair synchronization checks passed",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairCountMatch,
        name: "pair_count_match",
        meaning: "Whether read-pair counts match between mates",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads", "fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::StrictPass,
        name: "strict_pass",
        meaning: "Whether strict validation checks passed",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::FailureClass,
        name: "failure_class",
        meaning: "Validation failure classification",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TrimPolyg,
        name: "trim_polyg",
        meaning: "Whether polyG trimming was enabled",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MinPolygRun,
        name: "min_polyg_run",
        meaning: "Minimum polyG run length trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesTrimmedPolyg,
        name: "bases_trimmed_polyg",
        meaning: "Number of bases trimmed by polyG policy",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxBankId,
        name: "polyx_bank_id",
        meaning: "PolyX bank identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxBankHash,
        name: "polyx_bank_hash",
        meaning: "PolyX bank content hash",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxPreset,
        name: "polyx_preset",
        meaning: "PolyX bank preset name",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DamageMode,
        name: "damage_mode",
        meaning: "Damage trimming mode selected by stage policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ExecutionPolicy,
        name: "execution_policy",
        meaning: "Execution policy selected by stage governance",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RequestedTrim5pBases,
        name: "requested_trim_5p_bases",
        meaning: "Requested number of 5' bases trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RequestedTrim3pBases,
        name: "requested_trim_3p_bases",
        meaning: "Requested number of 3' bases trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::UdgClassification,
        name: "udg_classification",
        meaning: "UDG handling classification used for terminal-damage trimming policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ClassifiedFraction,
        name: "classified_fraction",
        meaning: "Fraction of reads classified by taxonomy screening",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::UnclassifiedFraction,
        name: "unclassified_fraction",
        meaning: "Fraction of reads unclassified by taxonomy screening",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Classifier,
        name: "classifier",
        meaning: "Classifier backend used for taxonomy screening",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReportFormat,
        name: "report_format",
        meaning: "Primary report format produced by taxonomy screening",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DatabaseCatalogId,
        name: "database_catalog_id",
        meaning: "Catalog identifier for taxonomy database selection",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DatabaseArtifactId,
        name: "database_artifact_id",
        meaning: "Artifact identifier for taxonomy database selection",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MinimumConfidence,
        name: "minimum_confidence",
        meaning: "Minimum classification confidence threshold",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::EmitUnclassified,
        name: "emit_unclassified",
        meaning: "Whether unclassified reads were retained in reporting outputs",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TopTaxa,
        name: "top_taxa",
        meaning: "Top taxa summary extracted from screening report",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::CtGaAsymmetryPre,
        name: "ct_ga_asymmetry_pre",
        meaning: "Terminal C>T / G>A asymmetry before damage trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: -1.0, max: 1.0 }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::CtGaAsymmetryPost,
        name: "ct_ga_asymmetry_post",
        meaning: "Terminal C>T / G>A asymmetry after damage trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: -1.0, max: 1.0 }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
];
