use crate::aggregate::schema::defs::{MetricDirection, MetricId, MetricRange, MetricSpec};
pub const METRIC_REGISTRY_FASTQ: [MetricSpec; 82] = [
    MetricSpec {
        id: MetricId::ContaminationRate,
        name: "contamination_rate",
        meaning: "Estimated contamination rate from screening",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &[
            "fastq.screen_taxonomy",
            "fastq.report_qc",
            "fastq.validate_reads",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RrnaFractionRemoved,
        name: "rrna_fraction_removed",
        meaning: "Fraction of reads removed by governed rRNA depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_rrna"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::HostFractionRemoved,
        name: "host_fraction_removed",
        meaning: "Fraction of reads removed by governed host depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_host"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminantFractionRemoved,
        name: "contaminant_fraction_removed",
        meaning: "Fraction of reads removed by governed reference contaminant depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_reference_contaminants"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DepletionSummary,
        name: "depletion_summary",
        meaning: "Structured governed depletion summary",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.deplete_rrna",
            "fastq.deplete_host",
            "fastq.deplete_reference_contaminants",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReferenceBytes,
        name: "reference_bytes",
        meaning: "Reference FASTA bytes presented to the index builder",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::IndexBytes,
        name: "index_bytes",
        meaning: "Total emitted reference index bytes",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::IndexFileCount,
        name: "index_file_count",
        meaning: "Number of emitted reference index files",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminationSummary,
        name: "contamination_summary",
        meaning: "Structured contamination summary",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GcPercent,
        name: "gc_percent",
        meaning: "GC percent",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: 100.0,
        }),
        stages: &["fastq.profile_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::LengthHistogram,
        name: "length_histogram",
        meaning: "Read length histogram",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.profile_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::CandidateAdapterCount,
        name: "candidate_adapter_count",
        meaning: "Number of candidate adapters reported by the governed observer",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterTrimmedFraction,
        name: "adapter_trimmed_fraction",
        meaning: "Fraction of reads with adapter evidence when the backend can estimate it",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.detect_adapters"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PrimerTrimmedFraction,
        name: "primer_trimmed_fraction",
        meaning: "Fraction of reads that required governed primer trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.normalize_primers"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::OrientationForwardFraction,
        name: "orientation_forward_fraction",
        meaning: "Fraction of reads reported in the governed forward orientation",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.normalize_primers"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadCount,
        name: "read_count",
        meaning: "Total reads counted in the length profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanReadLength,
        name: "mean_read_length",
        meaning: "Mean read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MaxReadLength,
        name: "max_read_length",
        meaning: "Maximum read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DistinctLengths,
        name: "distinct_lengths",
        meaning: "Number of distinct read lengths observed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::SequenceCount,
        name: "sequence_count",
        meaning: "Number of ranked overrepresented sequences emitted in the governed profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::FlaggedSequences,
        name: "flagged_sequences",
        meaning: "Number of overrepresented sequences above the governed flagging threshold",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TopFraction,
        name: "top_fraction",
        meaning: "Fraction carried by the dominant ranked overrepresented sequence",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DeltaMetrics,
        name: "delta_metrics",
        meaning: "Read/base retention deltas",
        direction: MetricDirection::HigherBetter,
        range: None,
        stages: &[
            "fastq.trim_reads",
            "fastq.filter_reads",
            "fastq.correct_errors",
        ],
        measured: false,
        derived: true,
    },
    MetricSpec {
        id: MetricId::PairedMode,
        name: "paired_mode",
        meaning: "Observed read layout during execution",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.trim_reads",
            "fastq.trim_polyg_tails",
            "fastq.remove_duplicates",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Tool,
        name: "tool",
        meaning: "Resolved tool identifier for the stage observation",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Threads,
        name: "threads",
        meaning: "Resolved thread count used by stage execution",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterPolicy,
        name: "adapter_policy",
        meaning: "Resolved adapter handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxPolicy,
        name: "polyx_policy",
        meaning: "Resolved polyX handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::NPolicy,
        name: "n_policy",
        meaning: "Resolved ambiguous-base handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminantPolicy,
        name: "contaminant_policy",
        meaning: "Resolved contaminant handling policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RawBackendReportFormat,
        name: "raw_backend_report_format",
        meaning: "Backend-native report format emitted by the stage",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.trim_reads",
            "fastq.trim_polyg_tails",
            "fastq.remove_duplicates",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DedupRate,
        name: "dedup_rate",
        meaning: "Fraction of input reads removed by duplicate filtering",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DedupMode,
        name: "dedup_mode",
        meaning: "Resolved duplicate-removal policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::KeepOrder,
        name: "keep_order",
        meaning: "Whether duplicate removal preserves input order",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateReads,
        name: "duplicates_removed",
        meaning: "Number of reads removed as duplicates",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateClassCount,
        name: "duplicate_class_count",
        meaning: "Number of duplicate classes represented in the governed summary",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DuplicateProvenanceJson,
        name: "duplicate_provenance_json",
        meaning: "Path to the governed duplicate provenance artifact",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterPreset,
        name: "adapter_preset",
        meaning: "Adapter preset identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankId,
        name: "adapter_bank_id",
        meaning: "Adapter bank identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterBankHash,
        name: "adapter_bank_hash",
        meaning: "Adapter bank hash",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AdapterOverrides,
        name: "adapter_overrides",
        meaning: "Adapter override parameters",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ValidatedInputs,
        name: "validated_inputs",
        meaning: "Number of FASTQ inputs validated",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ValidatedPairs,
        name: "validated_pairs",
        meaning: "Number of read pairs validated",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairSyncChecked,
        name: "pair_sync_checked",
        meaning: "Whether pair synchronization was evaluated",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairSyncPass,
        name: "pair_sync_pass",
        meaning: "Whether pair synchronization checks passed",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairCountMatch,
        name: "pair_count_match",
        meaning: "Whether read-pair counts match between mates",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads", "fastq.remove_duplicates"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::StrictPass,
        name: "strict_pass",
        meaning: "Whether strict validation checks passed",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::FailureClass,
        name: "failure_class",
        meaning: "Validation failure classification",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.validate_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TrimPolyg,
        name: "trim_polyg",
        meaning: "Whether polyG trimming was enabled",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MinPolygRun,
        name: "min_polyg_run",
        meaning: "Minimum polyG run length trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesTrimmedPolyg,
        name: "bases_trimmed_polyg",
        meaning: "Number of bases trimmed by polyG policy",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxBankId,
        name: "polyx_bank_id",
        meaning: "PolyX bank identifier",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxBankHash,
        name: "polyx_bank_hash",
        meaning: "PolyX bank content hash",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PolyxPreset,
        name: "polyx_preset",
        meaning: "PolyX bank preset name",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_polyg_tails"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DamageMode,
        name: "damage_mode",
        meaning: "Damage trimming mode selected by stage policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ExecutionPolicy,
        name: "execution_policy",
        meaning: "Execution policy selected by stage governance",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RequestedTrim5pBases,
        name: "requested_trim_5p_bases",
        meaning: "Requested number of 5' bases trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RequestedTrim3pBases,
        name: "requested_trim_3p_bases",
        meaning: "Requested number of 3' bases trimmed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::UdgClassification,
        name: "udg_classification",
        meaning: "UDG handling classification used for terminal-damage trimming policy",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ClassifiedFraction,
        name: "classified_fraction",
        meaning: "Fraction of reads classified by taxonomy screening",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::UnclassifiedFraction,
        name: "unclassified_fraction",
        meaning: "Fraction of reads unclassified by taxonomy screening",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::Classifier,
        name: "classifier",
        meaning: "Classifier backend used for taxonomy screening",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReportFormat,
        name: "report_format",
        meaning: "Primary report format produced by taxonomy screening",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DatabaseCatalogId,
        name: "database_catalog_id",
        meaning: "Catalog identifier for taxonomy database selection",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DatabaseArtifactId,
        name: "database_artifact_id",
        meaning: "Artifact identifier for taxonomy database selection",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MinimumConfidence,
        name: "minimum_confidence",
        meaning: "Minimum classification confidence threshold",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::EmitUnclassified,
        name: "emit_unclassified",
        meaning: "Whether unclassified reads were retained in reporting outputs",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TopTaxa,
        name: "top_taxa",
        meaning: "Top taxa summary extracted from screening report",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::CtGaAsymmetryPre,
        name: "ct_ga_asymmetry_pre",
        meaning: "Terminal C>T / G>A asymmetry before damage trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: -1.0,
            max: 1.0,
        }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::CtGaAsymmetryPost,
        name: "ct_ga_asymmetry_post",
        meaning: "Terminal C>T / G>A asymmetry after damage trimming",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: -1.0,
            max: 1.0,
        }),
        stages: &["fastq.trim_terminal_damage"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcRawDir,
        name: "raw_fastqc_dir",
        meaning: "Raw FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcTrimmedDir,
        name: "trimmed_fastqc_dir",
        meaning: "Trimmed FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AggregationEngine,
        name: "aggregation_engine",
        meaning: "Aggregation backend selected for governed QC reporting",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AggregationScope,
        name: "aggregation_scope",
        meaning: "Governed QC aggregation input scope",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcInputCount,
        name: "governed_qc_input_count",
        meaning: "Number of governed QC inputs aggregated into the report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcContributorStageIds,
        name: "governed_qc_contributor_stage_ids",
        meaning: "Distinct governed QC contributor stage identifiers",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcContributorToolIds,
        name: "governed_qc_contributor_tool_ids",
        meaning: "Distinct governed QC contributor tool identifiers",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcLineageHash,
        name: "governed_qc_lineage_hash",
        meaning: "Stable lineage fingerprint for governed QC inputs",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcSampleCount,
        name: "multiqc_sample_count",
        meaning: "Number of samples represented in the MultiQC report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcModuleCount,
        name: "multiqc_module_count",
        meaning: "Number of modules represented in the MultiQC report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcReport,
        name: "multiqc_report",
        meaning: "MultiQC report path",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcData,
        name: "multiqc_data",
        meaning: "MultiQC data directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
];
