use crate::aggregate::schema::defs::{MetricDirection, MetricId, MetricRange, MetricSpec};

pub const METRIC_REGISTRY_PROFILING_AND_REPORTING: [MetricSpec; 23] = [
    MetricSpec {
        id: MetricId::GcPercent,
        name: "gc_percent",
        meaning: "GC percent",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 100.0 }),
        stages: &["fastq.profile_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::LengthHistogram,
        name: "length_histogram",
        meaning: "Read length histogram",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.profile_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadCount,
        name: "read_count",
        meaning: "Total reads counted in the length profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MinReadLength,
        name: "min_read_length",
        meaning: "Minimum read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanReadLength,
        name: "mean_read_length",
        meaning: "Mean read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MedianReadLength,
        name: "median_read_length",
        meaning: "Median read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MaxReadLength,
        name: "max_read_length",
        meaning: "Maximum read length observed in the profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DistinctLengths,
        name: "distinct_lengths",
        meaning: "Number of distinct read lengths observed",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_read_lengths"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::SequenceCount,
        name: "sequence_count",
        meaning: "Number of ranked overrepresented sequences emitted in the governed profile",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::FlaggedSequences,
        name: "flagged_sequences",
        meaning: "Number of overrepresented sequences above the governed flagging threshold",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::TopFraction,
        name: "top_fraction",
        meaning: "Fraction carried by the dominant ranked overrepresented sequence",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.profile_overrepresented_sequences"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcRawDir,
        name: "raw_fastqc_dir",
        meaning: "Raw FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::QcTrimmedDir,
        name: "trimmed_fastqc_dir",
        meaning: "Trimmed FastQC directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AggregationEngine,
        name: "aggregation_engine",
        meaning: "Aggregation backend selected for governed QC reporting",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::AggregationScope,
        name: "aggregation_scope",
        meaning: "Governed QC aggregation input scope",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcInputCount,
        name: "governed_qc_input_count",
        meaning: "Number of governed QC inputs aggregated into the report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcContributorStageIds,
        name: "governed_qc_contributor_stage_ids",
        meaning: "Distinct governed QC contributor stage identifiers",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcContributorToolIds,
        name: "governed_qc_contributor_tool_ids",
        meaning: "Distinct governed QC contributor tool identifiers",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::GovernedQcLineageHash,
        name: "governed_qc_lineage_hash",
        meaning: "Stable lineage fingerprint for governed QC inputs",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcSampleCount,
        name: "multiqc_sample_count",
        meaning: "Number of samples represented in the MultiQC report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcModuleCount,
        name: "multiqc_module_count",
        meaning: "Number of modules represented in the MultiQC report",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange { min: 0.0, max: f64::INFINITY }),
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcReport,
        name: "multiqc_report",
        meaning: "MultiQC report path",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MultiqcData,
        name: "multiqc_data",
        meaning: "MultiQC data directory",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.report_qc"],
        measured: true,
        derived: false,
    },
];
