use crate::aggregate::schema::defs::{
    DerivedMetricSpec, MetricDirection, MetricId, MetricRange, MetricSpec,
};
use bijux_dna_core::prelude::DerivedMetricId;

pub const METRIC_REGISTRY_QUALITY: [MetricSpec; 15] = [
    MetricSpec {
        id: MetricId::BasesIn,
        name: "bases_in",
        meaning: "Number of input bases",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.validate_reads",
            "fastq.detect_adapters",
            "fastq.filter_reads",
            "fastq.deplete_rrna",
            "fastq.merge_pairs",
            "fastq.correct_errors",
            "fastq.report_qc",
            "fastq.extract_umis",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesOut,
        name: "bases_out",
        meaning: "Number of output bases",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.validate_reads",
            "fastq.detect_adapters",
            "fastq.filter_reads",
            "fastq.deplete_rrna",
            "fastq.merge_pairs",
            "fastq.correct_errors",
            "fastq.report_qc",
            "fastq.extract_umis",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::BasesTotal,
        name: "bases_total",
        meaning: "Total bases for stats",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.profile_reads"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairsIn,
        name: "pairs_in",
        meaning: "Number of input read pairs",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.validate_reads",
            "fastq.filter_reads",
            "fastq.deplete_rrna",
            "fastq.merge_pairs",
            "fastq.correct_errors",
            "fastq.report_qc",
            "fastq.extract_umis",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::PairsOut,
        name: "pairs_out",
        meaning: "Number of output read pairs",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.validate_reads",
            "fastq.filter_reads",
            "fastq.deplete_rrna",
            "fastq.merge_pairs",
            "fastq.correct_errors",
            "fastq.report_qc",
            "fastq.extract_umis",
            "fastq.screen_taxonomy",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsR1,
        name: "reads_r1",
        meaning: "Number of reads in R1",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge_pairs"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsR2,
        name: "reads_r2",
        meaning: "Number of reads in R2",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge_pairs"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsMerged,
        name: "reads_merged",
        meaning: "Number of merged reads",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge_pairs"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsUnmerged,
        name: "reads_unmerged",
        meaning: "Number of unmerged reads",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.merge_pairs"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQBefore,
        name: "mean_q_before",
        meaning: "Mean quality before processing",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.filter_reads",
            "fastq.correct_errors",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQAfter,
        name: "mean_q_after",
        meaning: "Mean quality after processing",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &[
            "fastq.trim_reads",
            "fastq.filter_reads",
            "fastq.correct_errors",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MeanQ,
        name: "mean_q",
        meaning: "Mean quality score",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: 45.0,
        }),
        stages: &[
            "fastq.validate_reads",
            "fastq.detect_adapters",
            "fastq.report_qc",
            "fastq.profile_reads",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::MergeRate,
        name: "merge_rate",
        meaning: "Merged reads / total reads",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.merge_pairs"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReadsWithUmi,
        name: "reads_with_umi",
        meaning: "Number of reads with extracted UMI annotations",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.extract_umis"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::KmerFixRate,
        name: "kmer_fix_rate",
        meaning: "Fraction of k-mers corrected",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.correct_errors"],
        measured: true,
        derived: false,
    },
];

pub const DERIVED_METRIC_REGISTRY: [DerivedMetricSpec; 4] = [
    DerivedMetricSpec {
        id: DerivedMetricId::ReadRetention,
        name: "read_retention",
        meaning: "reads_out / reads_in",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &[
            "fastq.trim_reads",
            "fastq.filter_reads",
            "fastq.correct_errors",
            "fastq.extract_umis",
        ],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::BaseRetention,
        name: "base_retention",
        meaning: "bases_out / bases_in",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &[
            "fastq.trim_reads",
            "fastq.filter_reads",
            "fastq.correct_errors",
            "fastq.extract_umis",
        ],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::MergeEfficiency,
        name: "merge_efficiency",
        meaning: "reads_merged / (reads_merged + reads_unmerged)",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.merge_pairs"],
    },
    DerivedMetricSpec {
        id: DerivedMetricId::ErrorReductionProxy,
        name: "error_reduction_proxy",
        meaning: "proxy for error reduction",
        direction: MetricDirection::HigherBetter,
        range: None,
        stages: &["fastq.correct_errors"],
    },
];
