use crate::aggregate::schema::defs::{MetricDirection, MetricId, MetricRange, MetricSpec};

pub const METRIC_REGISTRY_SCREENING_AND_REFERENCE: [MetricSpec; 9] = [
    MetricSpec {
        id: MetricId::ContaminationRate,
        name: "contamination_rate",
        meaning: "Estimated contamination rate from screening",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &[
            "fastq.screen_taxonomy",
            "fastq.report_qc",
            "fastq.validate_reads",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::RrnaFractionRemoved,
        name: "rrna_fraction_removed",
        meaning: "Fraction of reads removed by governed rRNA depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_rrna"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::HostFractionRemoved,
        name: "host_fraction_removed",
        meaning: "Fraction of reads removed by governed host depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_host"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminantFractionRemoved,
        name: "contaminant_fraction_removed",
        meaning: "Fraction of reads removed by governed reference contaminant depletion",
        direction: MetricDirection::LowerBetter,
        range: Some(MetricRange { min: 0.0, max: 1.0 }),
        stages: &["fastq.deplete_reference_contaminants"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::DepletionSummary,
        name: "depletion_summary",
        meaning: "Structured governed depletion summary",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &[
            "fastq.deplete_rrna",
            "fastq.deplete_host",
            "fastq.deplete_reference_contaminants",
        ],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ReferenceBytes,
        name: "reference_bytes",
        meaning: "Reference FASTA bytes presented to the index builder",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::IndexBytes,
        name: "index_bytes",
        meaning: "Total emitted reference index bytes",
        direction: MetricDirection::Neutral,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::IndexFileCount,
        name: "index_file_count",
        meaning: "Number of emitted reference index files",
        direction: MetricDirection::HigherBetter,
        range: Some(MetricRange {
            min: 0.0,
            max: f64::INFINITY,
        }),
        stages: &["fastq.index_reference"],
        measured: true,
        derived: false,
    },
    MetricSpec {
        id: MetricId::ContaminationSummary,
        name: "contamination_summary",
        meaning: "Structured contamination summary",
        direction: MetricDirection::Neutral,
        range: None,
        stages: &["fastq.screen_taxonomy"],
        measured: true,
        derived: false,
    },
];
