use super::{BenchmarkObservation, MetricsEnvelope};

impl BenchmarkObservation {
    #[must_use]
    #[allow(clippy::too_many_arguments)]
    pub fn v1(
        run_id: String,
        dataset_id: String,
        dataset_class: String,
        read_layout: String,
        stage_id: String,
        stage_instance_id: Option<String>,
        lineage_id: Option<String>,
        tool_id: String,
        tool_version: String,
        image_digest: String,
        container_digest: String,
        params_hash: String,
        input_hash: String,
        runtime_s: f64,
        memory_mb: f64,
        exit_code: i32,
        failure_kind: Option<String>,
        metrics: MetricsEnvelope,
        replicate_id: String,
        replicate_index: u32,
        warmup_policy: String,
        seed_policy: String,
        runner: String,
        platform: String,
        cpu: String,
        threads: u32,
        io_mode: String,
    ) -> Self {
        Self {
            schema_version: "bijux.bench.observation.v1".to_string(),
            run_id,
            dataset_id,
            dataset_class,
            read_layout,
            stage_id,
            stage_instance_id,
            lineage_id,
            tool_id,
            tool_version,
            image_digest,
            container_digest,
            params_hash,
            input_hash,
            runtime_s,
            memory_mb,
            exit_code,
            failure_kind,
            metrics,
            replicate_id,
            replicate_index,
            warmup_policy,
            seed_policy,
            runner,
            platform,
            cpu,
            threads,
            io_mode,
        }
    }
}
