use bijux_dna_core::ids::StageId;

use crate::stages::ids::{
    STAGE_CORRECT_ERRORS, STAGE_EXTRACT_UMIS, STAGE_FILTER_READS, STAGE_MERGE_PAIRS,
    STAGE_PROFILE_READS, STAGE_REPORT_QC, STAGE_SCREEN_TAXONOMY, STAGE_TRIM_READS,
    STAGE_VALIDATE_READS,
};

#[allow(dead_code)]
pub const CORE_STAGES: [StageId; 6] = [
    STAGE_VALIDATE_READS,
    STAGE_TRIM_READS,
    STAGE_MERGE_PAIRS,
    STAGE_CORRECT_ERRORS,
    STAGE_FILTER_READS,
    STAGE_PROFILE_READS,
];

#[allow(dead_code)]
pub const OPTIONAL_STAGES: [StageId; 3] =
    [STAGE_REPORT_QC, STAGE_EXTRACT_UMIS, STAGE_SCREEN_TAXONOMY];

#[allow(dead_code)]
pub const META_STAGES: [StageId; 0] = [];

#[allow(dead_code)]
pub const MUTATING_STAGES: [StageId; 5] = [
    STAGE_TRIM_READS,
    STAGE_MERGE_PAIRS,
    STAGE_CORRECT_ERRORS,
    STAGE_FILTER_READS,
    STAGE_EXTRACT_UMIS,
];

#[allow(dead_code)]
pub const LOSSLESS_STAGES: [StageId; 2] = [STAGE_VALIDATE_READS, STAGE_PROFILE_READS];

#[allow(dead_code)]
pub const OBSERVATIONAL_STAGES: [StageId; 4] =
    [STAGE_VALIDATE_READS, STAGE_PROFILE_READS, STAGE_REPORT_QC, STAGE_SCREEN_TAXONOMY];
