use bijux_dna_core::ids::StageId;

use crate::stages::ids::{
    STAGE_FILTER_READS, STAGE_MERGE_PAIRS, STAGE_TRIM_READS, STAGE_VALIDATE_READS,
};

pub const EVALUATED_STAGES: [StageId; 4] =
    [STAGE_VALIDATE_READS, STAGE_TRIM_READS, STAGE_MERGE_PAIRS, STAGE_FILTER_READS];
